name: Build hanwckf's kernal4.4 Padavan

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: 'target to compile'
        options:
        - CR660x
        - JCG-Q20
        - JCG-AC860M
        - JCG-836PRO
        - JCG-Y2
        - DIR-878
        - DIR-882
        - K2P
        - K2P-USB
        - NETGEAR-BZV
        - MR2600
        - MI-R3P
        - XY-C1
      uploadwet:
        type: boolean
        description: 'whether to upload firmware to wetransfer'
        default: 'true'
      pushplus:
        type: boolean
        description: 'whether to notify through pushplus'
        default: 'false'
env:
  REPOSITORY_URL: https://github.com/hanwckf/padavan-4.4.git
  TOOLCHAIN_URL: https://github.com/hanwckf/padavan-toolchain/releases/download/linux-4.4-v1.0/mipsel-linux-uclibc.tar.xz
  WORK_PATH: /opt/padavan-4.4
  TIME_ZONE: Asia/Shanghai
  FIRMWARE_AUTHOR: hanwckf
  FIRMWARE_PATH: /opt/firmwares
jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
        fakeroot kmod cpio git python3-docutils gettext automake autopoint \
        texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
        libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
        sudo timedatectl set-timezone "$TIME_ZONE"
    - name: Clone source code
      run: |
        git clone --depth=1 $REPOSITORY_URL $WORK_PATH
        cd $WORK_PATH/toolchain-mipsel
        mkdir -p toolchain-4.4.x
        wget $TOOLCHAIN_URL
        tar -xf mipsel-linux-uclibc.tar.xz -C toolchain-4.4.x
    - name: Set environment variables
      run: |
        git config --global log.date format:'%Y%m%d'
        cd $WORK_PATH
        echo "FIRMWARE_VERSION=$(git log -1 --pretty=format:"%cd")" >> $GITHUB_ENV
        echo "FIRMWARE_DATEPREFIX=$(date +"%Y%m%d")" >> $GITHUB_ENV
    - name: Custom config
      run: |
        cd $WORK_PATH/trunk
        if [ ! -f configs/templates/${{ github.event.inputs.target }}.config ] ; then
        echo "configs/templates/${{ github.event.inputs.target }}.config not found"
        exit 1
        fi
        cp -f configs/templates/${{ github.event.inputs.target }}.config .config
        sed -i "s/FIRMWARE_BUILDS_REV=.*/FIRMWARE_BUILDS_REV=${FIRMWARE_VERSION}/g" ./versions.inc
    - name: Build firmware
      run: |
        cd $WORK_PATH/trunk
        ./clear_tree
        fakeroot ./build_firmware_modify ${{ github.event.inputs.target }}
    - name: Organize firmware files
      id: organize
      run: |
        mkdir -p $FIRMWARE_PATH/
        cd $WORK_PATH/trunk/images
        for firmwarefile in $(ls *.trx)
        do sudo mv $firmwarefile $FIRMWARE_PATH/${FIRMWARE_DATEPREFIX}"_"${FIRMWARE_AUTHOR}"_"${{ github.event.inputs.target }}"_kernal4.4.trx"
        done
        cd $FIRMWARE_PATH
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "::set-output name=status::success"
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: steps.organize.outputs.status == 'success'
      with:
        name: Padavan44-packages
        path: ${{ env.FIRMWARE }}
    - name: Upload firmware to WeTransfer
      if: steps.organize.outputs.status == 'success' && github.event.inputs.uploadwet == 'true'
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer wet -s -p 16 --no-progress ${FIRMWARE} 2>&1 | tee wetransfer.log
        echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep -o -E "https?://[a-zA-Z0-9\.\/_&=@$%?~#-]*")"
        echo "WETRANSFER_URL=$(cat wetransfer.log | grep -o -E "https?://[a-zA-Z0-9\.\/_&=@$%?~#-]*")" >> $GITHUB_ENV
    - name: PushPlus Notification
      uses: vb1980/Action_PushPlus@master
      if: steps.organize.outputs.status == 'success' && github.event.inputs.pushplus == 'true'
      with:
        token: ${{ secrets.PUSHTOKEN }}
        title: ${{ github.event.inputs.target }}_Build_Completed
        content: Congratulations,<br/>&nbsp;&nbsp;Your **${{ github.event.inputs.target }}** padavan(4.4 kernal) firmware build completed!<br/>&nbsp;&nbsp;ğŸ®WeTransfer Download Url:${{ env.WETRANSFER_URL }}<br/>&nbsp;&nbsp;Enjoy itğŸˆğŸ!
