name: Build DSBox-DSR1

on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Build_ChongshengB_Padavan'
        required: true
        default: 'build'
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  watch:
    types: [started]
env:
  REPOSITORY_URL: https://github.com/chongshengB/rt-n56u.git
  TOOLCHAIN_URL: https://github.com/hanwckf/padavan-toolchain/releases/download/v1.1/mipsel-linux-uclibc.tar.xz
  WORK_PATH: /opt/rt-n56u
  TIME_ZONE: Asia/Shanghai
  TARGET_NAME: DSBox-DSR1
  FIRMWARE_VERSION: 20201015
  FIRMWARE_DATEPREFIX: $(date +"%Y%m%d")
  FIRMWARE_AUTHOR: chongshengB
  FIRMWARE_PATH: /opt/firmwares
  APPLY_RAINBOWTHEME: true
  APPLY_MobileCompatible: false
  RECOVERY_SSPBINREMOTEDOWNLOAD: false
  BUILD_OWNER: vb1980
  UPLOAD_COWTRANSFER: true
  UPLOAD_WETRANSFER: false
  SERVERCHAN_NOTIFICATION: true
jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot kmod \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
        sudo timedatectl set-timezone "$TIME_ZONE"
    - name: Clone source code
      run: |
        git clone --depth=1 $REPOSITORY_URL $WORK_PATH
        cd $WORK_PATH/toolchain-mipsel
        mkdir -p toolchain-3.4.x
        wget $TOOLCHAIN_URL
        tar -xvf mipsel-linux-uclibc.tar.xz -C toolchain-3.4.x
    - name: Set golang
      run: |
        cd /opt/hostedtoolcache/go
        rm -rf /opt/hostedtoolcache/go/1.14.13
        mv 1.15.6 1.14.13
    - name: Apply rainbow themes
      if: env.APPLY_RAINBOWTHEME == 'true'
      run: |
        cp -f rainbow/rainbowthemes.tar.xz $WORK_PATH/trunk/user/www
        cd $WORK_PATH/trunk/user/www
        sudo chmod +x ./rainbowthemes.tar.xz
        mkdir -p n56u_rainbow
        tar -xvf rainbowthemes.tar.xz -C n56u_rainbow
        sed -i "s/WEBUI_NAME=n56u_ribbon_fixed/WEBUI_NAME=n56u_rainbow/g" ./Makefile
    - name: Apply mobile compatible
      if: env.APPLY_RAINBOWTHEME == 'false' && env.APPLY_MobileCompatible == 'true'
      run: |
        cp -f originalui/main.css $WORK_PATH/trunk/user/www/n56u_ribbon_fixed/bootstrap/css
        cp -f originalui/popup.js $WORK_PATH/trunk/user/www/n56u_ribbon_fixed
        cp -f originalui/state.js $WORK_PATH/trunk/user/www/n56u_ribbon_fixed
    - name: Copy DSBox-DSR1 configs
      run: |
        cp -f dsr1/DSBox-DSR1.tar.xz $WORK_PATH/trunk
        cd $WORK_PATH/trunk
        sudo chmod +x ./DSBox-DSR1.tar.xz
        tar -xvf DSBox-DSR1.tar.xz
    - name: Recovery SSP bin files download from remote
      if: env.RECOVERY_SSPBINREMOTEDOWNLOAD == 'true'
      run: |
        cp -f ssp/shadowsocks.sh $WORK_PATH/trunk/user/shadowsocks/scripts
        cp -f ssp/defaults.c $WORK_PATH/trunk/user/shared
        cp -f ssp/variables.c $WORK_PATH//trunk/user/httpd
        cp -f ssp/Shadowsocks.asp $WORK_PATH/trunk/user/www/n56u_ribbon_fixed
        cd $WORK_PATH/trunk/user/shared
        sed -i "s#https://cdn.jsdelivr.net/gh/Padavan_CI/ssp/trojan#https://cdn.jsdelivr.net/gh/${BUILD_OWNER}/Padavan_CI/ssp/trojan#g" ./defaults.c
        sed -i "s#https://cdn.jsdelivr.net/gh/Padavan_CI/ssp/v2ray#https://cdn.jsdelivr.net/gh/${BUILD_OWNER}/Padavan_CI/ssp/v2ray#g" ./defaults.c
    - name: Update latest adg
      run: |
        cd $WORK_PATH/trunk/user/adguardhome
        sed -i "s#https://cdn.jsdelivr.net/gh/chongshengB/rt-n56u/trunk/user/adguardhome/AdGuardHome#https://cdn.jsdelivr.net/gh/${BUILD_OWNER}/Padavan_CI/adg/AdGuardHome#g" ./adguardhome.sh
    - name: Update latest v2ray
      run: |
        cp -f v2ray/v2ray-core-4.34.0.tar.gz $WORK_PATH/trunk/user/v2ray
        cd $WORK_PATH/trunk/user/v2ray
        sed -i "s#V2ray_VERSION := 4.31.2#V2ray_VERSION := 4.34.0#g" ./Makefile
    - name: Custom config
      run: |
        cd $WORK_PATH/trunk
        if [ ! -f configs/templates/$TARGET_NAME.config ] ; then
        echo "configs/templates/${TARGET_NAME}.config not found"
        exit 1
        fi
        cp -f configs/templates/$TARGET_NAME.config .config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
        ################################################################################################
        #Âõ†‰∏çÂêåÂûãÂè∑ÈÖçÁΩÆÂäüËÉΩ‰∏ç‰∏ÄÊ†∑ÔºåÊâÄ‰ª•ÂÖàÊääÈÖçÁΩÆÈ°πÂà†Èô§ÔºåÂ¶ÇÊûú‰Ω†Ëá™Â∑±Ë¶ÅÊ∑ªÂä†ÂÖ∂‰ªñÁöÑÔºå‰πüË¶ÅÂÜô‰∏äÂà†Èô§Ëøô‰∏ÄÊù°ÔºåÂàáËÆ∞ÔºÅÔºÅÔºÅ
        ################################################################################################
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER/d' .config #Âà†Èô§ÈÖçÁΩÆÈ°πSOFTETHERVPN
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT/d' .config #Âà†Èô§ÈÖçÁΩÆÈ°πSOFTETHERVPN
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD/d' .config #Âà†Èô§ÈÖçÁΩÆÈ°πSOFTETHERVPN   
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config #Âà†Èô§ÈÖçÁΩÆÈ°πSS plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' .config #Âà†Èô§ÈÖçÁΩÆÈ°πSS server
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' .config #Âà†Èô§ÈÖçÁΩÆÈ°πDNSFORWARDER
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ADBYBY/d' .config #Âà†Èô§ÈÖçÁΩÆÈ°πadbyby plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' .config #Âà†Èô§ÈÖçÁΩÆÈ°πadbyby plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPS/d' .config #Âà†Èô§ÈÖçÁΩÆÈ°πadbyby plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' .config #Âà†Èô§ÈÖçÁΩÆÈ°πadbyby plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ALIDDNS/d' .config #Âà†Èô§ÈÖçÁΩÆÈ°πÈòøÈáåDDNS
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNS/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_KUMASOCKS/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_IPT2SOCKS/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MICROSOCKS/d' .config
        #Ê†°Âõ≠ÁΩëÁõ∏ÂÖ≥ÂºÄÂßã
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' .config #Âà†Èô§ÈÖçÁΩÆÈ°πMENTOHUST
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' .config #Âà†Èô§ÈÖçÁΩÆÈ°πSCUTCLIENT
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NAPT66/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MINIEAP/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DOGCOM/d' .config
        #Ê†°Âõ≠ÁΩëÁõ∏ÂÖ≥ÁªìÊùü
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
        ######################################################################
        #‰ª•‰∏ãÈÄâÈ°πÊòØÂÆö‰πâ‰Ω†ÈúÄË¶ÅÁöÑÂäüËÉΩÔºày=ÈõÜÊàê,n=ÂøΩÁï•ÔºâÔºåÈáçÊñ∞ÂÜôÂÖ•Âà∞.configÊñá‰ª∂
        ######################################################################
        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER=n" >> .config #SOFTETHERVPN
        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT=n" >> .config #SOFTETHERVPN
        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD=n" >> .config #SOFTETHERVPN
        #ÁßëÂ≠¶Áõ∏ÂÖ≥
        echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=y" >> .config #SS plus+
        echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=y" >> .config #ÈõÜÊàêv2rayÊâßË°åÊñá‰ª∂Ôºà3.8MÂ∑¶Âè≥)ÔºåÂ¶ÇÊûú‰∏çÈõÜÊàêÔºå‰ºö‰ªéÁΩë‰∏ä‰∏ãËΩΩ‰∏ãÊù•ÊâßË°åÔºå‰∏çÂΩ±ÂìçÊ≠£Â∏∏‰ΩøÁî®
        echo "CONFIG_FIRMWARE_INCLUDE_TROJAN=y" >> .config #ÈõÜÊàêtrojanÊâßË°åÊñá‰ª∂(1.1MÂ∑¶Âè≥)ÔºåÂ¶ÇÊûú‰∏çÈõÜÊàêÔºå‰ºö‰ªéÁΩë‰∏ä‰∏ãËΩΩ‰∏ãÊù•ÊâßË°åÔºå‰∏çÂΩ±ÂìçÊ≠£Â∏∏‰ΩøÁî®
        echo "CONFIG_FIRMWARE_INCLUDE_SSOBFS=n" >> .config # simple-obfsÊ∑∑Ê∑ÜÊèí‰ª∂
        echo "CONFIG_FIRMWARE_INCLUDE_SSSERVER=n" >> .config #SS server
        echo "CONFIG_FIRMWARE_INCLUDE_KUMASOCKS=y" >> .config #socks5
        #
        echo "CONFIG_FIRMWARE_INCLUDE_IPT2SOCKS=y" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_MICROSOCKS=y" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_SRELAY=n" >> .config #ÂèØ‰ª•‰∏çÈõÜÊàê
        echo "CONFIG_FIRMWARE_INCLUDE_TUNSAFE=n" >> .config #TUNSAFE
        echo "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n" >> .config #DNSFORWARDER
        #
        echo "CONFIG_FIRMWARE_INCLUDE_FRPC=n" >> .config #ÂÜÖÁΩëÁ©øÈÄèFRPC
        echo "CONFIG_FIRMWARE_INCLUDE_FRPS=n" >> .config #ÂÜÖÁΩëÁ©øÈÄèFRPS
        #
        echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=n" >> .config #adbyby plus+
        echo "CONFIG_FIRMWARE_INCLUDE_KOOLPROXY=n" >> .config #KPÂπøÂëäËøáÊª§
        #
        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=n" >> .config #smartdns
        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN=n" >> .config #smartdns‰∫åËøõÂà∂Êñá‰ª∂
        echo "CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=y" >> .config
        #
        echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=y" >> .config #ÈòøÈáåDDNS
        echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=y" >> .config #zerotier ~1.3M
        #
        echo "CONFIG_FIRMWARE_INCLUDE_CADDY=n" >> .config #Âú®Á∫øÊñá‰ª∂ÁÆ°ÁêÜÊúçÂä°
        echo "CONFIG_FIRMWARE_INCLUDE_CADDYBIN=n" >> .config #ÈõÜÊàêcadduÊâßË°åÊñá‰ª∂ÔºåÊ≠§Êñá‰ª∂Êúâ13M,ËØ∑Ê≥®ÊÑèÂõ∫‰ª∂Â§ßÂ∞è„ÄÇÂ¶ÇÊûú‰∏çÈõÜÊàêÔºå‰ºö‰ªéÁΩë‰∏ä‰∏ãËΩΩ‰∏ãÊù•ÊâßË°åÔºå‰∏çÂΩ±ÂìçÊ≠£Â∏∏‰ΩøÁî®
        #
        echo "CONFIG_FIRMWARE_INCLUDE_WYY=n" >> .config #ÁΩëÊòì‰∫ëËß£ÈîÅ
        echo "CONFIG_FIRMWARE_INCLUDE_WYYBIN=n" >> .config #ÁΩëÊòì‰∫ëËß£ÈîÅGOÁâàÊú¨ÊâßË°åÊñá‰ª∂Ôºà4MÂ§öÔºâÊ≥®ÊÑèÂõ∫‰ª∂Ë∂ÖÂ§ßÂ∞è,‰∏çÈõÜÊàê‰ºöËá™Âä®‰∏ãËΩΩ
        #Ê†°Âõ≠ÁΩëÁõ∏ÂÖ≥ÂºÄÂßã
        echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> .config #MENTOHUST
        echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> .config #SCUTCLIENT
        echo "CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_MINIEAP=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_DOGCOM=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_NAPT66=n" >> .config
        #Ê†°Âõ≠ÁΩëÁõ∏ÂÖ≥ÁªìÊùü
        #########################################################################################
        #Ëá™ÂÆö‰πâÊ∑ªÂä†ÂÖ∂ÂÆÉÂäüËÉΩËØ∑ÂèÇËÄÉÊ∫êÁ†Åconfigs/templates/ÁõÆÂΩï‰∏ãÁöÑconfigÊñá‰ª∂„ÄÇÊåâÁÖß‰∏äÈù¢ÁöÑÊ†ºÂºèÊ∑ªÂä†Âç≥ÂèØ
        #Ê†ºÂºèÂ¶Ç‰∏ãÔºö
        #sed -i '/Ëá™ÂÆö‰πâÈ°π/d' .config
        #echo "Ëá™ÂÆö‰πâÈ°π=y" >> .config
        sed -i "s/FIRMWARE_BUILDS_REV=.*/FIRMWARE_BUILDS_REV=${FIRMWARE_VERSION}/g" ./versions.inc
        echo 'Êõ¥Êñ∞ÁâàÊú¨Âè∑Êó∂Èó¥'
        #########################################################################################
    - name: Build firmware
      run: |
        cd $WORK_PATH/trunk
        sudo ./clear_tree
        sudo ./build_firmware_modify $TARGET_NAME 0
        echo "FIRMWARE_DATEPREFIX=$(date +"%Y%m%d")" >> $GITHUB_ENV
    - name: Organize firmware files
      id: organize
      run: |
        mkdir -p $FIRMWARE_PATH/
        cd $WORK_PATH/trunk
        rainbow_Prefix=""
        if [ "${APPLY_RAINBOWTHEME}" = "true" ]
        then
        rainbow_Prefix="rainbow_"
        fi
        cd $WORK_PATH/trunk/images
        for firmwarefile in $(ls *.trx)
        do sudo mv $firmwarefile $FIRMWARE_PATH/${FIRMWARE_DATEPREFIX}"_"${FIRMWARE_AUTHOR}"_"${rainbow_Prefix}$firmwarefile
        done
        cd $FIRMWARE_PATH
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "::set-output name=status::success"
    - name : Upload packages
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success'
      with:
        name: Padavan-packages
        path: ${{ env.FIRMWARE }}
    - name: Upload firmware to cowtransfer
      if: steps.organize.outputs.status == 'success' && env.UPLOAD_COWTRANSFER == 'true'
      run: |
        curl -sL https://git.io/cowtransfer | sh
        ./cowtransfer-uploader -s -p 16 --hash ${FIRMWARE} 2>&1 | tee cowtransfer.log
        echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
        echo "COWTRANSFER_URL=$(cat cowtransfer.log | grep -o -E "https?://[a-zA-Z0-9\.\/_&=@$%?~#-]*")" >> $GITHUB_ENV
    - name: Upload firmware to WeTransfer
      if: steps.organize.outputs.status == 'success' && env.UPLOAD_WETRANSFER == 'true'
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer wet -s -p 16 --no-progress ${FIRMWARE} 2>&1 | tee wetransfer.log
        echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
        echo "WETRANSFER_URL=$(cat wetransfer.log | grep -o -E "https?://[a-zA-Z0-9\.\/_&=@$%?~#-]*")" >> $GITHUB_ENV
    - name: Remove obsolete firmwares on artifacts
      uses: c-hive/gha-remove-artifacts@v1.2.0
      if: steps.organizer.outputs.status == 'success' && env.UPLOAD_FIRMWARE == 'true'
      with:
        age: '1 day'
        skip-recent: 5
    - name: ServerChan Notification
      uses: emon100/Action-Serverchan@master
      if: steps.organize.outputs.status == 'success' && env.SERVERCHAN_NOTIFICATION == 'true'
      with:
        SCKEY: ${{ secrets.SCKEY }}
        text: ${{ env.TARGET_NAME }}_Build_Completed
        desp: Congratulations,
              
              
              Your **${{ env.TARGET_NAME }}** padavan firmware build completed!
              
              
              üêÆCowTransfer Download Url:${{ env.COWTRANSFER_URL }}
              
              
              Enjoy itüéàüéÅ!
              
              
              
