name: Build Xray

on: 
  workflow_dispatch:
    inputs:
      uploadanon:
        type: boolean
        description: 'whether to upload to anonfiles'
        default: 'false'
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22.0'
        check-latest: true
        cache-dependency-path: '**/go.sum'

    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt install upx git -y

    - name: Clone&Build source code
      id: build
      run: |
        git clone --depth=1 https://github.com/xtls/xray-core.git xray-core
        cd xray-core/main
        GOOS=linux GOARCH=mipsle go build -o ../../xraybin/xray -trimpath -ldflags "-s -w -buildid=" ./
        cd ../../xraybin
        #upx -9 xray
        shopt -s extglob
        rm -vrf !("xray")
        echo "xray=$PWD" >> $GITHUB_ENV
        echo "STATUS=success" >> $GITHUB_ENV

    - name : Upload packages
      uses: actions/upload-artifact@main
      if: env.STATUS == 'success'
      with:
        name: xray-packages
        path: ${{ env.xray }}
        
    - name: Upload xray bin to anonfiles
      if: env.STATUS == 'success' && github.event.inputs.uploadanon == 'true'
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer anon --no-progress ${v2ray} 2>&1 | tee anonfile.log
        echo "::warning file=anonfile.com::$(cat anonfile.log | grep -o -E "https?://[a-zA-Z0-9\.\/_&=@$%?~#-]*")"
        
    - name: Remove obsolete xray(s) on artifacts
      uses: Bonnie2980/gha-remove-artifacts@master
      if: env.STATUS == 'success'
      with:
        age: '1 day'
        skip-recent: 5
