name: Build BELL-A-040W-Q from vb1980 kvr repo

on: 
  workflow_dispatch:
    inputs:
      firmwarever:
        description: 'firmware''s version'
        required: true
        default: '20201015'
      busyboxver:
        type: choice
        description: 'busybox''s version'
        options:
        - 1.24.x
        - 1.34.1
        default: '1.24.x'
      ssp:
        type: boolean
        description: 'whether to apply the patch for download ssp bin from local or remote url'
        default: 'false'
      uploadwet:
        type: boolean
        description: 'whether to upload firmware to wetransfer'
        default: 'true'
      pushplus:
        type: boolean
        description: 'whether to notify through pushplus'
        default: 'false'
env:
  REPOSITORY_URL: https://github.com/vb1980/Padavan-KVR.git
  TOOLCHAIN_URL: https://github.com/hanwckf/padavan-toolchain/releases/download/v1.1/mipsel-linux-uclibc.tar.xz
  WORK_PATH: /opt/rt-n56u
  TIME_ZONE: Asia/Shanghai
  TARGET_NAME: BELL-A-040W-Q
  FIRMWARE_DATEPREFIX: $(date +"%Y%m%d")
  FIRMWARE_AUTHOR: vb1980
  FIRMWARE_PATH: /opt/firmwares
jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot kmod \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
        sudo timedatectl set-timezone "$TIME_ZONE"
    - name: Clone source code
      run: |
        git clone --depth=1 $REPOSITORY_URL $WORK_PATH
        cd $WORK_PATH/toolchain-mipsel
        mkdir -p toolchain-3.4.x
        wget $TOOLCHAIN_URL
        tar -xvf mipsel-linux-uclibc.tar.xz -C toolchain-3.4.x
    - name: Set golang
      run: |
        cp -f bashScripts/go.sh $(pwd)
        sudo chmod 777 ./go.sh
        bash ./go.sh
    - name: Set busybox's version to compile
      run: |
        cd $WORK_PATH/trunk/user/busybox
        sed -i "s/SRC_NAME=busybox.*/SRC_NAME=busybox-${{ github.event.inputs.busyboxver }}/g" ./Makefile
        cd $WORK_PATH/trunk
        sed -i "s/busybox_id=.*/busybox_id=\"${{ github.event.inputs.busyboxver }}\"/g" ./build_firmware_modify
    - name: Recovery SSP bin files download from remote
      if: github.event.inputs.ssp == 'true'
      run: |
        cp -f ssp/shadowsocks.sh $WORK_PATH/trunk/user/shadowsocks/scripts
        #cp -f ssp/defaults.c $WORK_PATH/trunk/user/shared
        #cp -f ssp/variables.c $WORK_PATH//trunk/user/httpd
        cp -f ssp/Shadowsocks.asp $WORK_PATH/trunk/user/www/n56u_ribbon_fixed
        cd $WORK_PATH/trunk/user/shared
        #sed -i "s#https://cdn.jsdelivr.net/gh/Padavan_CI/ssp/trojan#https://cdn.jsdelivr.net/gh/${{ github.repository_owner }}/Padavan_CI/ssp/trojan#g" ./defaults.c
        #sed -i "s#https://cdn.jsdelivr.net/gh/Padavan_CI/ssp/v2ray#https://cdn.jsdelivr.net/gh/${{ github.repository_owner }}/Padavan_CI/ssp/v2ray#g" ./defaults.c
    - name: Update latest adg
      run: |
        cp -f adg/adguardhome.sh $WORK_PATH/trunk/user/adguardhome
        #cp -f adg/defaults.c $WORK_PATH/trunk/user/shared
        #cp -f adg/variables.c $WORK_PATH//trunk/user/httpd
        cp -f adg/Advanced_adguardhome.asp $WORK_PATH/trunk/user/www/n56u_ribbon_fixed
        #cd $WORK_PATH/trunk/user/adguardhome
        #sed -i "s#https://cdn.jsdelivr.net/gh/chongshengB/rt-n56u/trunk/user/adguardhome/AdGuardHome#https://cdn.jsdelivr.net/gh/${{ github.repository_owner }}/Padavan_CI/adg/AdGuardHome#g" ./adguardhome.sh
    - name: Custom config
      run: |
        cd $WORK_PATH/trunk
        if [ ! -f configs/templates/$TARGET_NAME.config ] ; then
        echo "configs/templates/${TARGET_NAME}.config not found"
        exit 1
        fi
        cp -f configs/templates/$TARGET_NAME.config .config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
        ################################################################################################
        #å› ä¸åŒå‹å·é…ç½®åŠŸèƒ½ä¸ä¸€æ ·ï¼Œæ‰€ä»¥å…ˆæŠŠé…ç½®é¡¹åˆ é™¤ï¼Œå¦‚æœä½ è‡ªå·±è¦æ·»åŠ å…¶ä»–çš„ï¼Œä¹Ÿè¦å†™ä¸Šåˆ é™¤è¿™ä¸€æ¡ï¼Œåˆ‡è®°ï¼ï¼ï¼
        ################################################################################################
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER/d' .config #åˆ é™¤é…ç½®é¡¹SOFTETHERVPN
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT/d' .config #åˆ é™¤é…ç½®é¡¹SOFTETHERVPN
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD/d' .config #åˆ é™¤é…ç½®é¡¹SOFTETHERVPN   
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config #åˆ é™¤é…ç½®é¡¹SS plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' .config #åˆ é™¤é…ç½®é¡¹SS server
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' .config #åˆ é™¤é…ç½®é¡¹DNSFORWARDER
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ADBYBY/d' .config #åˆ é™¤é…ç½®é¡¹adbyby plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' .config #åˆ é™¤é…ç½®é¡¹FRP Client
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPS/d' .config #åˆ é™¤é…ç½®é¡¹FRPS Server
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NPC/d' .config #åˆ é™¤é…ç½®é¡¹NPC
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' .config #åˆ é™¤é…ç½®é¡¹TUNSAFE
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ALIDDNS/d' .config #åˆ é™¤é…ç½®é¡¹é˜¿é‡ŒDDNS
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ZEROTIER/d' .config #åˆ é™¤é…ç½®é¡¹ZEROTIER
        sed -i '/CONFIG_FIRMWARE_INCLUDE_CLOUDFLAREDDNS/d' .config #åˆ é™¤é…ç½®é¡¹CLOUDFLAREDDNS
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NVPPROXY/d' .config #åˆ é™¤é…ç½®é¡¹NVPPROXY
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DDNSTO/d' .config #åˆ é™¤é…ç½®é¡¹DDNSTO
        sed -i '/CONFIG_FIRMWARE_INCLUDE_WIREGUARD/d' .config #åˆ é™¤é…ç½®é¡¹WIREGUARD
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNS/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_KUMASOCKS/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_IPT2SOCKS/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MICROSOCKS/d' .config
        #æ ¡å›­ç½‘ç›¸å…³å¼€å§‹
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' .config #åˆ é™¤é…ç½®é¡¹MENTOHUST
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' .config #åˆ é™¤é…ç½®é¡¹SCUTCLIENT
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NAPT66/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MINIEAP/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DOGCOM/d' .config
        #æ ¡å›­ç½‘ç›¸å…³ç»“æŸ
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
        ######################################################################
        #ä»¥ä¸‹é€‰é¡¹æ˜¯å®šä¹‰ä½ éœ€è¦çš„åŠŸèƒ½ï¼ˆy=é›†æˆ,n=å¿½ç•¥ï¼‰ï¼Œé‡æ–°å†™å…¥åˆ°.configæ–‡ä»¶
        ######################################################################
        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER=n" >> .config #SOFTETHERVPN
        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT=n" >> .config #SOFTETHERVPN
        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD=n" >> .config #SOFTETHERVPN
        #ç§‘å­¦ç›¸å…³
        echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=y" >> .config #SS plus+
        echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=n" >> .config #é›†æˆv2rayæ‰§è¡Œæ–‡ä»¶ï¼ˆ3.8Må·¦å³)
        echo "CONFIG_FIRMWARE_INCLUDE_XRAY=y" >> .config #é›†æˆxrayæ‰§è¡Œæ–‡ä»¶(5.6Må·¦å³)ï¼Œå¯ä»¥ä»£æ›¿v2rayï¼Œæ³¨ï¼šå¦‚æœé—ªå­˜å¤ªå°ä¸å¤Ÿè¿˜æ˜¯å»ºè®®ä½¿ç”¨v2ray
        echo "CONFIG_FIRMWARE_INCLUDE_TROJAN=y" >> .config #é›†æˆtrojanæ‰§è¡Œæ–‡ä»¶(1.1Må·¦å³)
        echo "CONFIG_FIRMWARE_INCLUDE_SSOBFS=n" >> .config # simple-obfsæ··æ·†æ’ä»¶
        echo "CONFIG_FIRMWARE_INCLUDE_SSSERVER=n" >> .config #SS server
        echo "CONFIG_FIRMWARE_INCLUDE_KUMASOCKS=n" >> .config #socks5
        #
        echo "CONFIG_FIRMWARE_INCLUDE_IPT2SOCKS=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_MICROSOCKS=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_SRELAY=n" >> .config #å¯ä»¥ä¸é›†æˆ
        echo "CONFIG_FIRMWARE_INCLUDE_TUNSAFE=n" >> .config #TUNSAFE
        echo "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n" >> .config #DNSFORWARDER
        #
        echo "CONFIG_FIRMWARE_INCLUDE_FRPC=n" >> .config #å†…ç½‘ç©¿é€FRPC
        echo "CONFIG_FIRMWARE_INCLUDE_FRPS=n" >> .config #å†…ç½‘ç©¿é€FRPS
        echo "CONFIG_FIRMWARE_INCLUDE_NPC=n" >> .config #åˆ é™¤é…ç½®é¡¹NPC
        #
        echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=y" >> .config #adbyby plus+
        echo "CONFIG_FIRMWARE_INCLUDE_KOOLPROXY=y" >> .config #KPå¹¿å‘Šè¿‡æ»¤
        #
        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=n" >> .config #smartdns
        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN=n" >> .config #smartdnsäºŒè¿›åˆ¶æ–‡ä»¶
        echo "CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=y" >> .config
        #
        echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=y" >> .config #é˜¿é‡ŒDDNS
        echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=n" >> .config #zerotier ~1.3M
        echo "CONFIG_FIRMWARE_INCLUDE_CLOUDFLAREDDNS=n" >> .config #CLOUDFLAREDDNS
        echo "CONFIG_FIRMWARE_INCLUDE_NVPPROXY=n" >> .config #NVPPROXY
        echo "CONFIG_FIRMWARE_INCLUDE_DDNSTO=n" >> .config #DDNSTO
        echo "CONFIG_FIRMWARE_INCLUDE_WIREGUARD=n" >> .config #WIREGUARD
        #
        echo "CONFIG_FIRMWARE_INCLUDE_ALDRIVER=n" >> .config #é˜¿é‡Œäº‘ç›˜
        #
        echo "CONFIG_FIRMWARE_INCLUDE_CADDY=n" >> .config #åœ¨çº¿æ–‡ä»¶ç®¡ç†æœåŠ¡
        echo "CONFIG_FIRMWARE_INCLUDE_CADDYBIN=n" >> .config #é›†æˆcadduæ‰§è¡Œæ–‡ä»¶ï¼Œæ­¤æ–‡ä»¶æœ‰13M,è¯·æ³¨æ„å›ºä»¶å¤§å°ã€‚å¦‚æœä¸é›†æˆï¼Œä¼šä»ç½‘ä¸Šä¸‹è½½ä¸‹æ¥æ‰§è¡Œï¼Œä¸å½±å“æ­£å¸¸ä½¿ç”¨
        #
        echo "CONFIG_FIRMWARE_INCLUDE_WYY=n" >> .config #ç½‘æ˜“äº‘è§£é”
        echo "CONFIG_FIRMWARE_INCLUDE_WYYBIN=n" >> .config #ç½‘æ˜“äº‘è§£é”GOç‰ˆæœ¬æ‰§è¡Œæ–‡ä»¶ï¼ˆ4Må¤šï¼‰æ³¨æ„å›ºä»¶è¶…å¤§å°,ä¸é›†æˆä¼šè‡ªåŠ¨ä¸‹è½½
        #æ ¡å›­ç½‘ç›¸å…³å¼€å§‹
        echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> .config #MENTOHUST
        echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> .config #SCUTCLIENT
        echo "CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_MINIEAP=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_DOGCOM=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_NAPT66=n" >> .config
        #æ ¡å›­ç½‘ç›¸å…³ç»“æŸ
        #########################################################################################
        #è‡ªå®šä¹‰æ·»åŠ å…¶å®ƒåŠŸèƒ½è¯·å‚è€ƒæºç configs/templates/ç›®å½•ä¸‹çš„configæ–‡ä»¶ã€‚æŒ‰ç…§ä¸Šé¢çš„æ ¼å¼æ·»åŠ å³å¯
        #æ ¼å¼å¦‚ä¸‹ï¼š
        #sed -i '/è‡ªå®šä¹‰é¡¹/d' .config
        #echo "è‡ªå®šä¹‰é¡¹=y" >> .config
        sed -i "s/FIRMWARE_BUILDS_REV=.*/FIRMWARE_BUILDS_REV=${{ github.event.inputs.firmwarever }}/g" ./versions.inc
        echo 'æ›´æ–°ç‰ˆæœ¬å·æ—¶é—´'
        #########################################################################################
    - name: Build firmware
      run: |
        cd $WORK_PATH/trunk
        sudo ./clear_tree
        sudo ./build_firmware_modify $TARGET_NAME 0
        echo "FIRMWARE_DATEPREFIX=$(date +"%Y%m%d")" >> $GITHUB_ENV
    - name: Organize firmware files
      id: organize
      run: |
        mkdir -p $FIRMWARE_PATH/
        cd $WORK_PATH/trunk/images
        for firmwarefile in $(ls *.trx)
        do sudo mv $firmwarefile $FIRMWARE_PATH/${FIRMWARE_DATEPREFIX}"_"${FIRMWARE_AUTHOR}"_"$firmwarefile
        done
        cd $FIRMWARE_PATH
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "STATUS=success" >> $GITHUB_ENV
    - name : Upload packages
      uses: actions/upload-artifact@main
      if: env.STATUS == 'success'
      with:
        name: Padavan-packages
        path: ${{ env.FIRMWARE }}
    - name: Upload firmware to WeTransfer
      if: env.STATUS == 'success' && github.event.inputs.uploadwet == 'true'
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer wet -s -p 16 --no-progress ${FIRMWARE} 2>&1 | tee wetransfer.log
        echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep -o -E "https?://[a-zA-Z0-9\.\/_&=@$%?~#-]*")"
        echo "WETRANSFER_URL=$(cat wetransfer.log | grep -o -E "https?://[a-zA-Z0-9\.\/_&=@$%?~#-]*")" >> $GITHUB_ENV
    - name: Remove obsolete firmwares on artifacts
      uses: c-hive/gha-remove-artifacts@v1.2.0
      if: env.STATUS == 'success'
      with:
        age: '1 day'
        skip-recent: 5
    - name: PushPlus Notification
      uses: vb1980/Action_PushPlus@master
      if: env.STATUS == 'success' && github.event.inputs.pushplus == 'true'
      with:
        token: ${{ secrets.PUSHTOKEN }}
        title: ${{ env.TARGET_NAME }}_Build_Completed
        content: Congratulations,<br/>&nbsp;&nbsp;Your **${{ env.TARGET_NAME }}** padavan firmware build completed!<br/>&nbsp;&nbsp;ğŸ®WeTransfer Download Url:${{ env.WETRANSFER_URL }}<br/>&nbsp;&nbsp;Enjoy itğŸˆğŸ!
